### ISSUE TITLE
Can you update this more frequently?

### ISSUE THREAD

**Issue by mldangelo** [bpb27/political_twitter_archive#2]
Once per day would be awesome! 

Thanks.

**Comment by michaelb87** [comment]
I would be more than happy if there were at least monthly updates :)

Thanks

**Comment by bpb27** [comment]
Sorry I'll try and work on that. If you need data for something for now, you can get it via the website. Example:

http://www.trumptwitterarchive.com/data/rogerjstonejr/2009.json
